# jdr_engine/persistence/protocols.py
"""Protocoles de persistance — indépendants de l'implémentation."""
from __future__ import annotations

from typing import Protocol

from jdr_engine.domain.character.character import Character


class CharacterRepository(Protocol):
    def save(self, character: Character) -> None: ...
    def get_by_id(self, character_id: str) -> Character | None: ...
    def get_by_name(self, name: str, owner_id: str) -> Character | None: ...
    def list_by_owner(self, owner_id: str) -> list[Character]: ...
    def delete(self, character_id: str) -> bool: ...
    def name_exists(self, name: str, owner_id: str, exclude_id: str | None = None) -> bool: ...
